name: 2) Build Android (.aab for Play Store)
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'index.html'
      - 'manifest.json'
      - 'capacitor.config.json'
      - 'package.json'
      - '*.png'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
      - name: Arrange folders
        run: |
          mkdir -p
